#program to find average of ages of 10 players
age1=int(input("enter the age"))
age2=int(input("enter the age"))
age3=int(input("enter the age"))
age4=int(input("enter the age"))
age5=int(input("enter the age"))
age6=int(input("enter the age"))
age7=int(input("enter the age"))
age8=int(input("enter the age"))
age9=int(input("enter the age"))
age10=int(input("enter the age"))
avg=((age1+age2+age3+age4+age5+age6+age7+age8+age9+age10)/10)
print("average of the ages of 10 players",avg)
